language: node_js
node_js:
  - "4"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
cache:
  directories:
  - node_modules
  - bower_components
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
script:
  - grunt test
  - hack/verify-dist.sh
